Downgrade some common warnings to info
doitsujin/dxvk pull request #2221
Opened 2021-08-08 10:26 UTC by DadSchoorse

Reduces stderr spam when running tests with `DXVK_LOG_LEVEL=warn`.

2021-08-08 11:08 UTC, Joshua-Ashton requested changes

2021-08-08 11:08 UTC, Joshua-Ashton commented on src/d3d9/d3d9_format.cpp
> +      Logger::info("D3D9: VK_FORMAT_A4R4G4B4_UNORM_PACK16_EXT -> VK_FORMAT_B4G4R4A4_UNORM_PACK16");
I think we can keep this one as a warning for drivers with no 4444 formats because it could cause actual issues. (ie. border color)

2021-08-08 20:33 UTC, Joshua-Ashton commented
May want to do this for D3D11 too?

2021-08-09 09:57 UTC, K0bin approved these changes

2021-08-09 11:14 UTC, Joshua-Ashton approved these changes

2021-08-09 11:17 UTC, merged