RFC: Use memory mapped files for managed textures
doitsujin/dxvk pull request #2524
Opened 2022-03-04 22:47 UTC by K0bin

In order to finally fix some of our address space problems, I took a page out of Gallium Nines book.

Managed textures now use memory mapped files to store the internal data. The data is suballocated from 4KB (totally arbitrary) memory mapped files. This allows us to map and unmap that memory as we see fit. This only impacts managed textures, systemmem textures still use the DXVKBuffer to store their data because they can be used with `GetRenderTargetData` to read back data from the GPU. I don't think those are a problem anyway. Buffers are also unchanged. It's possible to extend this to buffers but I'd like to get some feedback first.

Unmapping follows a simple heuristic: We track the frame in which a texture was last used with `LockRect`, `AddDirtyRect` or when it was actually uploaded. If that was more than 16 frames ago or we've crossed the threshold of 512MB for mapped textures, we unmap. I hope that's good enough for games that keep the pointer around after calling Unlock. If it's not we can either try to tweak the heuristic, come up with something smarter or just disable it using a config option. I'd rather not punish decent D3D9 games that just happen to use too many high res managed textures because some do stupid things that aren't supposed to be allowed.

All of this is disabled in 64 bit builds of course.

The branch is basically a prototype. It works pretty well with Borderlands 2 and Witcher 2, both of which use a ton of managed textures. I'd like to get some feedback on this. Should we also extend this to buffers? Do you have any other ideas for the unmap heuristic?

2022-03-04 23:49 UTC, DadSchoorse requested changes
Sorry for the technicalities, I saw the `delete this;` and got very annoyed about lifetimes :frog:

2022-03-04 23:49 UTC, DadSchoorse commented on src/d3d9/d3d9_mem.h
> +      std::vector<D3D9MemoryChunk*> m_chunks;
Imo this should be a `std::vector<std::unique_ptr<D3D9MemoryChunk>>`, then you won't have to manually delete the chunk after removing it from `m_chunks`.

2022-03-04 23:49 UTC, DadSchoorse commented on src/d3d9/d3d9_mem.cpp
> +      delete this;
I hate everything about this. You can't simply commit suicide, you don't even know that this was allocated with `new`.

2022-03-04 23:49 UTC, DadSchoorse commented on src/d3d9/d3d9_mem.cpp
> +      delete this;
Imo, call `m_allocator->FreeChunk(this);` and that could call delete. But even that's still a bit eww.

2022-03-04 23:49 UTC, DadSchoorse commented on src/d3d9/d3d9_mem.h
> +      D3D9MemoryChunk();
where is the default allocator used?

2022-03-04 23:49 UTC, DadSchoorse commented on src/d3d9/d3d9_mem.h
> +      D3D9MemoryChunk(D3D9MemoryAllocator* Allocator, uint32_t Size);
Imo, this should be private and D3D9MemoryAllocator a friend.

2022-03-04 23:49 UTC, DadSchoorse commented on src/d3d9/d3d9_mem.h
> +  class D3D9MemoryChunk {
This should probably delete copy and move constructor/assignment.

2022-03-05 14:43 UTC, K0bin commented
Thanks for the review. I guess my lack of C++ experience is really showing here.

2022-03-05 16:14 UTC, K0bin commented
Addressed the feedback.

2022-03-05 22:02 UTC, DadSchoorse commented
Honestly I would prefer something like this https://github.com/DadSchoorse/dxvk/commit/7a800f4d443b7f360cf64cff784e48e4c9706749, which also has the added advantage that it doesn't break dxvk-native.

2022-03-06 00:05 UTC, wils0nyan commented
every time I try to merge this in and run Return of Reckoning (warhammer online) with the latest wine and mesa the launcher crashes straight away

wine: Unhandled page fault on read access to 0000000C at address 6244DDDC (thread 0110), starting debugger...

Unhandled exception: page fault on read access to 0x0000000c in 32-bit code (0x6244dddc).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:6244dddc ESP:079df7b0 EBP:00000000 EFLAGS:00010256(  R- --  I  Z-A-P- )
 EAX:00000003 EBX:079df8b8 ECX:00c77278 EDX:00000000
 ESI:00000003 EDI:00000000
Stack dump:
0x079df7b0:  00c6a338 00d0b940 00010000 00000000
0x079df7c0:  00000023 079df8b8 00000000 6a2d961e
0x079df7d0:  0ae20000 e7c18000 00010000 00d059b0
0x079df7e0:  00000000 079df8b8 079df8f8 62462fa2
0x079df7f0:  079df8b8 00000003 00000000 00000000
0x079df800:  626a8ac4 626a92ec 626a8ac4 626a8884
Backtrace:
=>0 0x6244dddc in d3d9 (+0xdddc) (0x00000000)
0x6244dddc d3d9+0xdddc: movl    0xc(%edx),%eax


includes even the frog patch

2022-03-06 00:15 UTC, K0bin commented
@wils0nyan Can you make an apitrace?

2022-03-06 23:56 UTC, wils0nyan commented
[ror-apitrace.tar.gz](https://github.com/doitsujin/dxvk/files/8193816/ror-apitrace.tar.gz)

ok here it is I'm not sure if this is useful

this is unrelated but even though the launcher loads without the unmap merge the box is still blacked out/flashes details every now and then

2022-03-11 13:37 UTC, K0bin commented
The launcher crash should be fixed.

2022-03-16 21:31 UTC, DadSchoorse commented on src/d3d9/meson.build
> +  'd3d9_mem.cpp'
Please add a trailing comma.

2022-03-21 03:47 UTC, wils0nyan commented
can confirm that the crash is gone but also have the following going:
git revert 4e6db51230d78354e2a86a23943c590f72d43c5e
git revert 14df2f7251002892436b3e2dafb8db19be1624d9
(because they supposedly fixed that pretty quickly in radv)

and merged:
shader_replacement
dogma-fix
unmap-managed

no crash all good so far

2022-03-21 12:42 UTC, K0bin commented
@wils0nyan What game are you talking about and why do you randomly revert and merge branches of mine?

The shader_replacement branch was just a debugging experiment and will do absolutely nothing for you.

2022-03-21 14:01 UTC, wils0nyan commented
> @wils0nyan What game are you talking about and why do you randomly revert and merge branches of mine?
> 
> The shader_replacement branch was just a debugging experiment and will do absolutely nothing for you. Those reverts will only break games unless you're using a couple of very specific commits of RADV.

I just try whatever I see usually. dxvk doesn't take very long to compile and I don't have to worry about rebooting or reloading xservers. I haven't noticed any problems doing those reverts with the latest mesa but i've only been playing warhammer online.

2022-03-21 14:02 UTC, K0bin commented
Actually, the fixes you reverted will even cause crashes in some cases. Please don't mindlessly revert commits.

2022-03-21 14:05 UTC, wils0nyan commented
> Actually, the fixes you reverted will even cause crashes in some cases. Please don't mindlessly revert commits.

ok but they are simple reverts really and all the commits do is disable a feature I can disable thru the conf file anyway.

2022-03-21 14:15 UTC, K0bin commented
> ok but they are simple reverts really and all the commits do is disable a feature I can disable thru the conf file anyway.

No, 4e6db51230d78354e2a86a23943c590f72d43c5e doesn't disable the feature. It fixes a crash. The feature will still get enabled with that commit reverted.

Also, why are you even disabling that? It's essentially free on newer RADV drivers and on anything else we only enable it when it's necessary.

2022-03-23 15:27 UTC, K0bin commented
Alternatively we could unmap based on LRU and only past a certain memory threshold?

2022-03-28 21:04 UTC, K0bin commented
I played through half of Mirrors Edge with this on the Steam Deck. It works great with texture streaming in UE3.

2022-04-04 13:23 UTC, Blisto91 commented
Great work.
If you have any specific games that needs testing just say so

2022-04-04 13:30 UTC, K0bin commented
Basically anything that's 32bit and currently crashes.

2022-04-06 03:53 UTC, TheIronWolfModding commented
Hi,
If I understand correctly, this approach saves process' address space when MANAGED pool is used?

Is it possible to extend this approach to optionally do this for D3DPOOL_SYSTEMMEM?  There's a family of games that uses SYSTEMMEM texture for each DEFAULT one, perhaps because it does some CPU processing on them, sometimes.   If those textures could be pushed out of process' address space it would be a huge win there.   Thanks!

2022-04-06 10:05 UTC, K0bin commented
> Is it possible to extend this approach to optionally do this for D3DPOOL_SYSTEMMEM? There's a family of games that mirrors SYSTEMMEM texture for each DEFAULT one, perhaps because it does some CPU processing on them, sometimes. If those textures could be pushed out of process' address space it would be a huge win there.

It's definitely possible but a bit more annoying because you can write to SYSTEMMEM textures on the GPU. Can you open an issue for that and attach an apitrace? I can look into extending this for SYSTEMMEM after landing the initial version.

Which games are we talking about anyway?

2022-04-06 16:26 UTC, TheIronWolfModding commented
I am messing with a 32bit game called GTR2.  However, same or similar game engine is used by rFactor, Automobilista and dozen of other games, so I am _guessing_ they might benefit as well.

One important detail about those games is that they are semi-open.  They are not opensource, but they are by design made in such a way, that people can create their own cars/tracks, and customize nearly any aspect of the simulation.  There are plenty of tools and a lot of stuff is adjustable via text configuration files.

The stock GTR2 won't run out of memory.  But if you use some modern community content with highly detailed meshes and high resolution textures that's where the problem surfaces.  It is not possible to simulate real events running, say 67 cars, because game runs out of memory at 30 cars.

I am in a middle of debugging, but it seems that game creates sysmem texture, and it keeps them around (creating the address space pressure), and dynamically manages matching default textures.  I see some calls to LockRect/AddDirtyRect/UpdateTexture etc.  I do not yet understand why that is done that way, but I think at least some of the processing is on the CPU side.  Buffers contribute to memory pressure too, because even though they seem to go to default pool, they are DYNAMIC usage, so they seem to eat up process' address space as well, but not sure how big of a problem that is.

All that said, would issue with an apitrace still help?

2022-04-19 23:00 UTC, K0bin commented
Renamed some symbols from _MANAGED to something a bit more generic in case we ever decide to extend this to other pool types.

2022-04-20 19:57 UTC, TheIronWolfModding commented on src/d3d9/d3d9_device.cpp
> +#ifdef D3D9_USE_MEM_FILE_FOR_MANAGED
this is missing the rename :)  I noticed while updating my fork...

2022-05-31 02:11 UTC, qinlili23333 commented
Some games really work better now with this version, but cannot solve https://github.com/doitsujin/dxvk/issues/2417
Saints Row 2 now stuck at loading screen (while master branch build will directly crash)
I tested it on Windows 11 Preview (22621.1). Spec:i7-11800H, RTX3060 6G, 64G DDR4, 1440P internal display with another 2160P monitor plugged in

2022-06-02 12:53 UTC, K0bin commented
Superseded by #2663

2022-06-02 12:53 UTC, closed without merging