[d3d9] Add VkInterop interfaces
doitsujin/dxvk pull request #2948
Opened 2022-09-21 21:04 UTC by Joshua-Ashton

Should provide everything needed for VR.

2022-09-21 21:06 UTC, Joshua-Ashton commented
cc: @TheIronWolfModding

2022-09-22 16:18 UTC, K0bin requested changes
Looks mostly fine, just some small nits wrt locking.

2022-09-22 16:18 UTC, K0bin commented on src/d3d9/d3d9_interfaces.h
> +   * Can be called to ensure no D3D9 device methods
You should probably mention that this doesn't do anything if the device wasn't created with the MULTITHREAD flag.

2022-09-22 16:18 UTC, K0bin commented on src/d3d9/d3d9_interfaces.h
> +  virtual void STDMETHODCALLTYPE TransitionTextureLayout(
You should add a note clarifying that the caller is expected to synchronize the device.
Same thing for most of the other functions.

2022-09-22 16:58 UTC, merged