[d3d9] Add ID3D9VkInteropDevice::CreateImage to create custom textures/surfaces
doitsujin/dxvk pull request #4352
Opened 2024-10-12 02:48 UTC by AlpyneDreams

This extends the D3D9 device interop interface to allow creating surfaces and textures with custom image usage flags. This is useful, for example, if you want to add usage flags like `VK_IMAGE_USAGE_STORAGE_BIT` for writing to D3D9 textures in compute shaders.

2024-10-12 08:12 UTC, doitsujin requested changes
nit, also one question: Is there a universe where you might need view formats that don't exactly match the D3D9 image format?

2024-10-12 08:12 UTC, doitsujin commented on src/d3d9/d3d9_surface.h
> +            HANDLE*                   pSharedHandle = nullptr);
Not a huge fan of default parameters where  we can avoid them, can we just make a separate constructor instead that just forwards to this one?

2024-10-12 08:12 UTC, doitsujin commented on src/d3d9/d3d9_texture.h
> +            HANDLE*                   pSharedHandle = nullptr);
same here

2024-10-12 09:44 UTC, PatrickvL commented on src/d3d9/d3d9_common_texture.h
> +    // Additional paramters for ID3D9VkInteropDevice
nit: spelling of parameters

2024-10-12 09:45 UTC, PatrickvL reviewed
Small spelling error in a comment

2024-10-15 04:01 UTC, AlpyneDreams commented
> nit, also one question: Is there a universe where you might need view formats that don't exactly match the D3D9 image format?

I can't think of a situation where that'd be needed but I imagine one might exist. Could always add another field to `D3D9VkExtImageDesc` for setting a separate view format later on.

2024-10-15 08:09 UTC, merged